"use client"

import { motion } from "framer-motion"
import { useEffect, useState } from "react"
import {
  Ban,
  Brain,
  Car,
  Home,
  ShieldCheck,
  TrendingUp,
  RefreshCw,
  type LucideIcon,
} from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { cn } from "@/lib/utils"
import { insights, recommendedActions, type Insight } from "@/lib/aqi-data"
import { AiReportPanel } from "./ai-report-panel"
import { useLocation } from "@/components/location-provider"

const actionIcons: Record<string, LucideIcon> = {
  shield: ShieldCheck,
  ban: Ban,
  car: Car,
  home: Home,
}

const severityStyle: Record<Insight["severity"], string> = {
  high: "bg-destructive/10 text-destructive",
  medium: "bg-[color:var(--warning)]/10 text-[color:var(--warning)]",
  low: "bg-success/10 text-[color:var(--success)]",
}

export function AiInsights() {
  const { selectedArea } = useLocation()
  const [currentInsights, setCurrentInsights] = useState(insights)
  const [refreshing, setRefreshing] = useState(false)

  useEffect(() => {
    setCurrentInsights(insights.map((insight) => ({ ...insight, detail: `${selectedArea.name}: ${insight.detail} Current AQI is ${selectedArea.aqi}.` })))
  }, [selectedArea])

  async function refreshInsights() {
    setRefreshing(true)
    await Promise.resolve()
    setCurrentInsights(insights.map((insight, index) => index === 0 ? { ...insight, detail: `${selectedArea.name}: ${insight.detail} Current AQI is ${selectedArea.aqi}.` } : { ...insight, detail: `${selectedArea.name}: ${insight.detail}` }))
    setRefreshing(false)
  }

  return (
    <section aria-label="AI insights" className="grid gap-4 lg:grid-cols-3">
      {/* Insights list */}
      <Card className="lg:col-span-2">
        <CardHeader className="flex-row items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <Brain className="size-[18px]" />
            </div>
            <div>
              <CardTitle>AI Insights</CardTitle>
              <CardDescription className="mt-0.5">
                Generated by HetEvoAgent models
              </CardDescription>
            </div>
          </div>
          <div className="flex items-center gap-2"><Button variant="outline" size="sm" className="gap-1.5" onClick={refreshInsights} disabled={refreshing}><RefreshCw className={cn("size-3.5", refreshing && "animate-spin")} />{refreshing ? "Refreshing" : "Refresh"}</Button><Badge variant="outline" className="gap-1"><span className="size-1.5 rounded-full bg-success" />Auto</Badge></div>
        </CardHeader>
        <CardContent className="flex flex-col gap-3">
          {currentInsights.map((insight, i) => (
            <motion.article
              key={insight.id}
              initial={{ opacity: 0, x: -12 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.08, duration: 0.4 }}
              className="flex gap-3 rounded-xl border border-border bg-muted/40 p-3.5 transition-colors hover:bg-muted"
            >
              <div
                className={cn(
                  "flex size-9 shrink-0 items-center justify-center rounded-lg",
                  severityStyle[insight.severity],
                )}
              >
                <TrendingUp className="size-[18px]" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <h3 className="truncate text-sm font-semibold">
                    {insight.title}
                  </h3>
                  <Badge
                    variant="secondary"
                    className={cn("capitalize", severityStyle[insight.severity])}
                  >
                    {insight.severity}
                  </Badge>
                </div>
                <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
                  {insight.detail}
                </p>
                <div className="mt-2 flex items-center gap-2">
                  <div className="h-1.5 w-24 overflow-hidden rounded-full bg-border">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${insight.confidence}%` }}
                      transition={{ delay: 0.2 + i * 0.08, duration: 0.8 }}
                      className="h-full rounded-full bg-primary"
                    />
                  </div>
                  <span className="text-xs text-muted-foreground">
                    {insight.confidence}% confidence
                  </span>
                </div>
              </div>
            </motion.article>
          ))}
        </CardContent>
      </Card>

      {/* Recommended actions */}
      <Card>
        <CardHeader>
          <CardTitle>Recommended Actions</CardTitle>
          <CardDescription className="mt-0.5">
            Based on current air quality
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-2.5">
          {recommendedActions.map((action, i) => {
            const Icon = actionIcons[action.icon] ?? ShieldCheck
            return (
              <motion.div
                key={action.id}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.06, duration: 0.35 }}
                className="flex items-center gap-3 rounded-xl border border-border p-3 transition-colors hover:border-primary/40 hover:bg-primary/5"
              >
                <div className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <Icon className="size-4" />
                </div>
                <span className="text-sm font-medium">{action.label}</span>
              </motion.div>
            )
          })}
          <div className="mt-1 w-full">
            <AiReportPanel location={selectedArea.name} />
          </div>
        </CardContent>
      </Card>
    </section>
  )
}
